---
#
# Ansible managed
#
repository:
  description: Install docker_compose on your system.
  homepage: https://buluma.github.io/
  topics: docker, dockercompose, compose, ansible, molecule, tox, playbook
