---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    docker_compose_url:
      "https://github.com/docker/compose/releases/download/{{ docker_compose_version
      }}/docker-compose-{{ ansible_facts['system'] | lower }}-{{ docker_compose_architecture
      }}"

  roles:
    - role: buluma.docker_compose
